In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("Datasets/dirty_cafe_sales.csv")

In [12]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [15]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [16]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [19]:
df = pd.read_csv("Datasets/dirty_cafe_sales.csv", na_values=["UNKNOWN","ERROR"], dtype={'Transaction ID':str,'Item':'category','Payment Method':'category', 'Location':'category'}, parse_dates=['Transaction Date'])

In [20]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [21]:
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [23]:
df.dtypes

Transaction ID                 str
Item                      category
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method            category
Location                  category
Transaction Date    datetime64[us]
dtype: object

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   category
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   category
 6   Location          6039 non-null   category
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: category(3), datetime64[us](1), float64(3), str(1)
memory usage: 420.7 KB

In [25]:
df.describe()

          Quantity  Price Per Unit  Total Spent            Transaction Date
count  9521.000000     9467.000000  9498.000000                        9540
mean      3.028463        2.949984     8.924352  2023-07-01 23:00:31.698113
min       1.000000        1.000000     1.000000         2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000         2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000         2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000         2023-10-02 00:00:00
max       5.000000        5.000000    25.000000         2023-12-31 00:00:00
std       1.419007        1.278450     6.009919                         NaN

In [27]:
df.shape

(10000, 8)

In [28]:
df.describe(include="all")

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9031,9521.000000,9467.000000,9498.000000,6822,6039,9540
unique,10000,8,NaN,NaN,NaN,3,2,NaN
top,TXN_1961373,Juice,NaN,NaN,NaN,Digital Wallet,Takeaway,NaN
freq,1,1171,NaN,NaN,NaN,2291,3022,NaN
mean,NaN,NaN,3.028463,2.949984,8.924352,NaN,NaN,2023-07-01 23:00:31.698113
min,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,2023-01-01 00:00:00
25%,NaN,NaN,2.000000,2.000000,4.000000,NaN,NaN,2023-04-01 00:00:00
50%,NaN,NaN,3.000000,3.000000,8.000000,NaN,NaN,2023-07-02 00:00:00
75%,NaN,NaN,4.000000,4.000000,12.000000,NaN,NaN,2023-10-02 00:00:00
max,NaN,NaN,5.000000,5.000000,25.000000,NaN,NaN,2023-12-31 00:00:00
std,NaN,NaN,1.419007,1.278450,6.009919,NaN,NaN,NaN

In [30]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Payment Method'].value_count(dropna)